import ROOT
from ROOT import *
import os
from array import array
import math
from math import *
import sys
import glob
import csv
import ctypes
from ctypes import *
import XRootD
from pyxrootd import client
import numpy as np

#from future import division
def FindAndSetMax(*args):
        if len(args) == 1: args = args[0]
        maximum = 0.0
        for i in args:
                i.SetStats(0)
                t = i.GetMaximum()
                if t > maximum:
                        maximum = t
        for j in args:
                j.GetYaxis().SetRangeUser(1,maximum*1.35)#should be 1.35 (below as well)
                j.SetLineWidth(2)
        return maximum*1.35

def GoodPlotFormat(H, *args): # Handy little script for color/line/fill/point/etc...
        try: H.SetStats(0)
        except: print " ------------ [  No stats box found!  ]"
        if args[0] == 'thickline':
                H.SetLineColor(args[1])
                H.SetLineWidth(2)
        if args[0] == 'thinline':
                H.SetLineColor(args[1])
                H.SetLineWidth(1)
                H.SetLineStyle(args[2])
        if args[0] == 'fill':
                H.SetLineColor(args[1])
                #H.SetFillColorAlpha(args[1], 1.0)
                H.SetFillColor(args[1])
                H.SetFillStyle(args[2])
        if args[0] == 'markers':
                H.SetLineColor(args[1])
                H.SetMarkerColor(args[1])
                H.SetMarkerStyle(args[2])
                H.SetMarkerSize(1.1)
        H.GetXaxis().SetTitleSize(0.04)

        if args[0] == 'dashed':
                H.SetLineColor(args[1])
                H.SetLineWidth(1)
                H.SetLineStyle(7)
def convertAsymGraph(TG, template, name):
        Hist = template.Clone(name)
        for i in range(1,Hist.GetNbinsX()+1):
                Hist.SetBinContent(i,0.)

#       print("Number of points: "+str(TG.GetN()))

        for i in range(TG.GetN()):
        #       Hist.SetBinContent(i+1,TG.GetY()[i]*(TG.GetErrorXlow(i)+TG.GetErrorXhigh(i)))
                Hist.SetBinContent(i+1,TG.GetY()[i])
#               print("Y= "+str(TG.GetY()[i]))
#               print("error xlow + error xhigh = "+str(TG.GetErrorXlow(i)+TG.GetErrorXhigh(i)))
                Hist.SetBinError(i+1, TG.GetErrorY(i))
        return Hist

def convertBinNHist(H, template, name):
        Hist = template.Clone(name)
        for i in range(1,Hist.GetNbinsX()+1):
                Hist.SetBinContent(i,H.GetBinContent(i))
                Hist.SetBinError(i,H.GetBinError(i))
        return Hist

def MakeNBinsFromMinToMax(N,Min,Max): # helper for making large bin arrays makes N bins between Min and Max (same as you're feed to a TH1F)
        BINS = []
        for i in range(N+1):
                BINS.append(Min+(i*(Max-Min)/N))
        return BINS

def DBBW(H):
        for i in range(1,H.GetNbinsX()+1):
                C = H.GetBinContent(i)
                E = H.GetBinError(i)
                W = H.GetBinWidth(i)
                H.SetBinContent(i, C/W)
                H.SetBinError(i, E/W)
        return H
def AddCMSLumi(pad, fb, extra):
        cmsText     = "CMS " + extra
        cmsTextFont   = 61
        lumiTextSize     = 0.45
        lumiTextOffset   = 0.15
        cmsTextSize      = 0.5
        cmsTextOffset    = 0.15
        H = pad.GetWh()
        W = pad.GetWw()
        l = pad.GetLeftMargin()
        t = pad.GetTopMargin()
        r = pad.GetRightMargin()
        b = pad.GetBottomMargin()
        e = 0.025
        pad.cd()
        lumiText = str(fb)+" fb^{-1} (13 TeV)"
        latex = TLatex()
        latex.SetNDC()
        latex.SetTextAngle(0)
        latex.SetTextColor(kBlack)
        extraTextSize = 0.76*cmsTextSize
        latex.SetTextFont(42)
        latex.SetTextAlign(31)
        latex.SetTextSize(lumiTextSize*t)
        latex.DrawLatex(1-r,1-t+lumiTextOffset*t,lumiText)
        pad.cd()
        latex.SetTextFont(cmsTextFont)
        latex.SetTextSize(cmsTextSize*t)
        latex.SetTextAlign(11)
        latex.DrawLatex(0.1265, 1-t+lumiTextOffset*t, cmsText)
        pad.Update()

def makePull(data, bkg):
	pull = data.Clone("pull")
	pull.Divide(bkg)
	GoodPlotFormat(pull, "markers", ROOT.kBlack, 20)
	return pull

def makeCheap(data):
	cheapline = data.Clone("cheapline")
	cheapline.Divide(data)
	for i in range(1, cheapline.GetNbinsX()+1):
		cheapline.SetBinContent(i,1)
	cheapline.GetYaxis().SetTitle("2017/2018")
	cheapline.GetYaxis().SetTitleSize(0.1)
	cheapline.GetYaxis().SetNdivisions(6)
	cheapline.GetYaxis().SetLabelSize(0.145)
	cheapline.GetYaxis().SetTitleOffset(0.275)
	cheapline.GetYaxis().CenterTitle(True)
	cheapline.GetYaxis().SetRangeUser(0.,1.5)
	GoodPlotFormat(cheapline, "thinline", ROOT.kGray, 4)
	cheapline.GetXaxis().SetTitleSize(0.1925)
	cheapline.GetXaxis().SetLabelSize(0.16)
	cheapline.GetXaxis().SetTitleOffset(0.84)
	return cheapline
	

class drawRData:
	def __init__(self, name, GJ_Select, GJ_Fat, GJ_PN, GJ_PN_high, WG_Select, WG_Fat, WG_PN, WG_PN_high, ZG_Select, ZG_Fat, ZG_PN, ZG_PN_high, M50_Select, M50_Fat, M50_PN, M50_PN_high, DataC_Select, DataC_Fat, DataC_PN, DataC_PN_high):
		gROOT.SetBatch(True)

		self.i = TFile.Open(GJ_Select, "READ")
		self.i.ls();

		self.h1_GJ_sel = self.i.Get("softdrop")
		self.h2_GJ_sel = self.i.Get("jet_pt")
		
		GoodPlotFormat(self.h1_GJ_sel, 'thickline', kBlue)
		GoodPlotFormat(self.h2_GJ_sel, 'thickline', kBlue)
		
		self.h1_GJ_sel.SetYTitle("Events")	
		self.h2_GJ_sel.SetYTitle("Events")	

		self.j = TFile.Open(GJ_Fat, "READ")
		self.j.ls();

		self.h1_GJ_fat = self.j.Get("softdrop")
		self.h2_GJ_fat = self.j.Get("jet_pt")
		self.h3_GJ_fat = self.j.Get("PN_QCD")
		self.h4_GJ_fat = self.j.Get("PN_Xbb")
		self.h5_GJ_fat = self.j.Get("PN_Xcc")
		self.h6_GJ_fat = self.j.Get("PN_Xqq")
		self.h7_GJ_fat = self.j.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h2_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h3_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h4_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h5_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h6_GJ_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h7_GJ_fat, 'thickline', kGreen)
		
		self.k = TFile.Open(GJ_PN, "READ")
		self.k.ls();

		self.h1_GJ_pn = self.k.Get("softdrop")
		self.h2_GJ_pn = self.k.Get("jet_pt")
		self.h3_GJ_pn = self.k.Get("PN_QCD")
		self.h4_GJ_pn = self.k.Get("PN_Xbb")
		self.h5_GJ_pn = self.k.Get("PN_Xcc")
		self.h6_GJ_pn = self.k.Get("PN_Xqq")
		self.h7_GJ_pn = self.k.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h2_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h3_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h4_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h5_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h6_GJ_pn, 'thickline', kRed)
		GoodPlotFormat(self.h7_GJ_pn, 'thickline', kRed)

		self.l = TFile.Open(GJ_PN_high, "READ")
		self.l.ls();

		self.h1_GJ_pn_high = self.l.Get("softdrop")
		self.h2_GJ_pn_high = self.l.Get("jet_pt")
		self.h3_GJ_pn_high = self.l.Get("PN_QCD")
		self.h4_GJ_pn_high = self.l.Get("PN_Xbb")
		self.h5_GJ_pn_high = self.l.Get("PN_Xcc")
		self.h6_GJ_pn_high = self.l.Get("PN_Xqq")
		self.h7_GJ_pn_high = self.l.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h2_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h3_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h4_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h5_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h6_GJ_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h7_GJ_pn_high, 'thickline', kViolet)

		
		FindAndSetMax(self.h1_GJ_sel, self.h1_GJ_fat, self.h1_GJ_pn, self.h1_GJ_pn_high)
		FindAndSetMax(self.h2_GJ_sel, self.h2_GJ_fat, self.h2_GJ_pn, self.h2_GJ_pn_high)
		FindAndSetMax(self.h3_GJ_fat, self.h3_GJ_pn, self.h3_GJ_pn_high)
		FindAndSetMax(self.h4_GJ_fat, self.h4_GJ_pn, self.h4_GJ_pn_high)
		FindAndSetMax(self.h5_GJ_fat, self.h5_GJ_pn, self.h5_GJ_pn_high)
		FindAndSetMax(self.h6_GJ_fat, self.h6_GJ_pn, self.h6_GJ_pn_high)
		FindAndSetMax(self.h7_GJ_fat, self.h7_GJ_pn, self.h7_GJ_pn_high)


		self.m = TFile.Open(WG_Select, "READ")
		self.m.ls();

		self.h1_WG_sel = self.m.Get("softdrop")
		self.h2_WG_sel = self.m.Get("jet_pt")
		
		GoodPlotFormat(self.h1_WG_sel, 'thickline', kBlue)
		GoodPlotFormat(self.h2_WG_sel, 'thickline', kBlue)
		
		self.h1_WG_sel.SetYTitle("Events")	
		self.h2_WG_sel.SetYTitle("Events")	

		self.n = TFile.Open(WG_Fat, "READ")
		self.n.ls();

		self.h1_WG_fat = self.n.Get("softdrop")
		self.h2_WG_fat = self.n.Get("jet_pt")
		self.h3_WG_fat = self.n.Get("PN_QCD")
		self.h4_WG_fat = self.n.Get("PN_Xbb")
		self.h5_WG_fat = self.n.Get("PN_Xcc")
		self.h6_WG_fat = self.n.Get("PN_Xqq")
		self.h7_WG_fat = self.n.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h2_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h3_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h4_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h5_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h6_WG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h7_WG_fat, 'thickline', kGreen)
		
		self.o = TFile.Open(WG_PN, "READ")
		self.o.ls();

		self.h1_WG_pn = self.o.Get("softdrop")
		self.h2_WG_pn = self.o.Get("jet_pt")
		self.h3_WG_pn = self.o.Get("PN_QCD")
		self.h4_WG_pn = self.o.Get("PN_Xbb")
		self.h5_WG_pn = self.o.Get("PN_Xcc")
		self.h6_WG_pn = self.o.Get("PN_Xqq")
		self.h7_WG_pn = self.o.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h2_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h3_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h4_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h5_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h6_WG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h7_WG_pn, 'thickline', kRed)

		self.p = TFile.Open(WG_PN_high, "READ")
		self.p.ls();

		self.h1_WG_pn_high = self.p.Get("softdrop")
		self.h2_WG_pn_high = self.p.Get("jet_pt")
		self.h3_WG_pn_high = self.p.Get("PN_QCD")
		self.h4_WG_pn_high = self.p.Get("PN_Xbb")
		self.h5_WG_pn_high = self.p.Get("PN_Xcc")
		self.h6_WG_pn_high = self.p.Get("PN_Xqq")
		self.h7_WG_pn_high = self.p.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h2_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h3_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h4_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h5_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h6_WG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h7_WG_pn_high, 'thickline', kViolet)

		
		FindAndSetMax(self.h1_WG_sel, self.h1_WG_fat, self.h1_WG_pn, self.h1_WG_pn_high)
		FindAndSetMax(self.h2_WG_sel, self.h2_WG_fat, self.h2_WG_pn, self.h2_WG_pn_high)
		FindAndSetMax(self.h3_WG_fat, self.h3_WG_pn, self.h3_WG_pn_high)
		FindAndSetMax(self.h4_WG_fat, self.h4_WG_pn, self.h4_WG_pn_high)
		FindAndSetMax(self.h5_WG_fat, self.h5_WG_pn, self.h5_WG_pn_high)
		FindAndSetMax(self.h6_WG_fat, self.h6_WG_pn, self.h6_WG_pn_high)
		FindAndSetMax(self.h7_WG_fat, self.h7_WG_pn, self.h7_WG_pn_high)

		self.q = TFile.Open(ZG_Select, "READ")
		self.q.ls();

		self.h1_ZG_sel = self.q.Get("softdrop")
		self.h2_ZG_sel = self.q.Get("jet_pt")
		
		GoodPlotFormat(self.h1_ZG_sel, 'thickline', kBlue)
		GoodPlotFormat(self.h2_ZG_sel, 'thickline', kBlue)
		
		self.h1_ZG_sel.SetYTitle("Events")	
		self.h2_ZG_sel.SetYTitle("Events")	

		self.r = TFile.Open(ZG_Fat, "READ")
		self.r.ls();

		self.h1_ZG_fat = self.r.Get("softdrop")
		self.h2_ZG_fat = self.r.Get("jet_pt")
		self.h3_ZG_fat = self.r.Get("PN_QCD")
		self.h4_ZG_fat = self.r.Get("PN_Xbb")
		self.h5_ZG_fat = self.r.Get("PN_Xcc")
		self.h6_ZG_fat = self.r.Get("PN_Xqq")
		self.h7_ZG_fat = self.r.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h2_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h3_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h4_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h5_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h6_ZG_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h7_ZG_fat, 'thickline', kGreen)
		
		self.s = TFile.Open(ZG_PN, "READ")
		self.s.ls();

		self.h1_ZG_pn = self.s.Get("softdrop")
		self.h2_ZG_pn = self.s.Get("jet_pt")
		self.h3_ZG_pn = self.s.Get("PN_QCD")
		self.h4_ZG_pn = self.s.Get("PN_Xbb")
		self.h5_ZG_pn = self.s.Get("PN_Xcc")
		self.h6_ZG_pn = self.s.Get("PN_Xqq")
		self.h7_ZG_pn = self.s.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h2_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h3_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h4_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h5_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h6_ZG_pn, 'thickline', kRed)
		GoodPlotFormat(self.h7_ZG_pn, 'thickline', kRed)

		self.t = TFile.Open(ZG_PN_high, "READ")
		self.t.ls();

		self.h1_ZG_pn_high = self.t.Get("softdrop")
		self.h2_ZG_pn_high = self.t.Get("jet_pt")
		self.h3_ZG_pn_high = self.t.Get("PN_QCD")
		self.h4_ZG_pn_high = self.t.Get("PN_Xbb")
		self.h5_ZG_pn_high = self.t.Get("PN_Xcc")
		self.h6_ZG_pn_high = self.t.Get("PN_Xqq")
		self.h7_ZG_pn_high = self.t.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h2_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h3_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h4_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h5_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h6_ZG_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h7_ZG_pn_high, 'thickline', kViolet)

		
		FindAndSetMax(self.h1_ZG_sel, self.h1_ZG_fat, self.h1_ZG_pn, self.h1_ZG_pn_high)
		FindAndSetMax(self.h2_ZG_sel, self.h2_ZG_fat, self.h2_ZG_pn, self.h2_ZG_pn_high)
		FindAndSetMax(self.h3_ZG_fat, self.h3_ZG_pn, self.h3_ZG_pn_high)
		FindAndSetMax(self.h4_ZG_fat, self.h4_ZG_pn, self.h4_ZG_pn_high)
		FindAndSetMax(self.h5_ZG_fat, self.h5_ZG_pn, self.h5_ZG_pn_high)
		FindAndSetMax(self.h6_ZG_fat, self.h6_ZG_pn, self.h6_ZG_pn_high)
		FindAndSetMax(self.h7_ZG_fat, self.h7_ZG_pn, self.h7_ZG_pn_high)

		self.u = TFile.Open(M50_Select, "READ")
		self.u.ls();

		self.h1_M50_sel = self.u.Get("softdrop")
		self.h2_M50_sel = self.u.Get("jet_pt")
		
		GoodPlotFormat(self.h1_M50_sel, 'thickline', kBlue)
		GoodPlotFormat(self.h2_M50_sel, 'thickline', kBlue)
		
		self.h1_M50_sel.SetYTitle("Events")	
		self.h2_M50_sel.SetYTitle("Events")	

		self.v = TFile.Open(M50_Fat, "READ")
		self.v.ls();

		self.h1_M50_fat = self.v.Get("softdrop")
		self.h2_M50_fat = self.v.Get("jet_pt")
		self.h3_M50_fat = self.v.Get("PN_QCD")
		self.h4_M50_fat = self.v.Get("PN_Xbb")
		self.h5_M50_fat = self.v.Get("PN_Xcc")
		self.h6_M50_fat = self.v.Get("PN_Xqq")
		self.h7_M50_fat = self.v.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h2_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h3_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h4_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h5_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h6_M50_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h7_M50_fat, 'thickline', kGreen)
		
		self.w = TFile.Open(M50_PN, "READ")
		self.w.ls();

		self.h1_M50_pn = self.w.Get("softdrop")
		self.h2_M50_pn = self.w.Get("jet_pt")
		self.h3_M50_pn = self.w.Get("PN_QCD")
		self.h4_M50_pn = self.w.Get("PN_Xbb")
		self.h5_M50_pn = self.w.Get("PN_Xcc")
		self.h6_M50_pn = self.w.Get("PN_Xqq")
		self.h7_M50_pn = self.w.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h2_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h3_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h4_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h5_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h6_M50_pn, 'thickline', kRed)
		GoodPlotFormat(self.h7_M50_pn, 'thickline', kRed)

		self.x = TFile.Open(M50_PN_high, "READ")
		self.x.ls();

		self.h1_M50_pn_high = self.x.Get("softdrop")
		self.h2_M50_pn_high = self.x.Get("jet_pt")
		self.h3_M50_pn_high = self.x.Get("PN_QCD")
		self.h4_M50_pn_high = self.x.Get("PN_Xbb")
		self.h5_M50_pn_high = self.x.Get("PN_Xcc")
		self.h6_M50_pn_high = self.x.Get("PN_Xqq")
		self.h7_M50_pn_high = self.x.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h2_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h3_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h4_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h5_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h6_M50_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h7_M50_pn_high, 'thickline', kViolet)

		
		FindAndSetMax(self.h1_M50_sel, self.h1_M50_fat, self.h1_M50_pn, self.h1_M50_pn_high)
		FindAndSetMax(self.h2_M50_sel, self.h2_M50_fat, self.h2_M50_pn, self.h2_M50_pn_high)
		FindAndSetMax(self.h3_M50_fat, self.h3_M50_pn, self.h3_M50_pn_high)
		FindAndSetMax(self.h4_M50_fat, self.h4_M50_pn, self.h4_M50_pn_high)
		FindAndSetMax(self.h5_M50_fat, self.h5_M50_pn, self.h5_M50_pn_high)
		FindAndSetMax(self.h6_M50_fat, self.h6_M50_pn, self.h6_M50_pn_high)
		FindAndSetMax(self.h7_M50_fat, self.h7_M50_pn, self.h7_M50_pn_high)
		

		self.y = TFile.Open(DataC_Select, "READ")
		self.y.ls();

		self.h1_DataC_sel = self.y.Get("softdrop")
		self.h2_DataC_sel = self.y.Get("jet_pt")
		
		GoodPlotFormat(self.h1_DataC_sel, 'thickline', kBlue)
		GoodPlotFormat(self.h2_DataC_sel, 'thickline', kBlue)
		
		self.h1_DataC_sel.SetYTitle("Events")	
		self.h2_DataC_sel.SetYTitle("Events")	

		self.z = TFile.Open(DataC_Fat, "READ")
		self.z.ls();

		self.h1_DataC_fat = self.z.Get("softdrop")
		self.h2_DataC_fat = self.z.Get("jet_pt")
		self.h3_DataC_fat = self.z.Get("PN_QCD")
		self.h4_DataC_fat = self.z.Get("PN_Xbb")
		self.h5_DataC_fat = self.z.Get("PN_Xcc")
		self.h6_DataC_fat = self.z.Get("PN_Xqq")
		self.h7_DataC_fat = self.z.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h2_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h3_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h4_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h5_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h6_DataC_fat, 'thickline', kGreen)
		GoodPlotFormat(self.h7_DataC_fat, 'thickline', kGreen)
		
		self.a = TFile.Open(DataC_PN, "READ")
		self.a.ls();

		self.h1_DataC_pn = self.a.Get("softdrop")
		self.h2_DataC_pn = self.a.Get("jet_pt")
		self.h3_DataC_pn = self.a.Get("PN_QCD")
		self.h4_DataC_pn = self.a.Get("PN_Xbb")
		self.h5_DataC_pn = self.a.Get("PN_Xcc")
		self.h6_DataC_pn = self.a.Get("PN_Xqq")
		self.h7_DataC_pn = self.a.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h2_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h3_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h4_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h5_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h6_DataC_pn, 'thickline', kRed)
		GoodPlotFormat(self.h7_DataC_pn, 'thickline', kRed)

		self.b = TFile.Open(DataC_PN_high, "READ")
		self.b.ls();

		self.h1_DataC_pn_high = self.b.Get("softdrop")
		self.h2_DataC_pn_high = self.b.Get("jet_pt")
		self.h3_DataC_pn_high = self.b.Get("PN_QCD")
		self.h4_DataC_pn_high = self.b.Get("PN_Xbb")
		self.h5_DataC_pn_high = self.b.Get("PN_Xcc")
		self.h6_DataC_pn_high = self.b.Get("PN_Xqq")
		self.h7_DataC_pn_high = self.b.Get("PN_AllQQ")
		
		GoodPlotFormat(self.h1_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h2_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h3_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h4_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h5_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h6_DataC_pn_high, 'thickline', kViolet)
		GoodPlotFormat(self.h7_DataC_pn_high, 'thickline', kViolet)

		
		FindAndSetMax(self.h1_DataC_sel, self.h1_DataC_fat, self.h1_DataC_pn, self.h1_DataC_pn_high)
		FindAndSetMax(self.h2_DataC_sel, self.h2_DataC_fat, self.h2_DataC_pn, self.h2_DataC_pn_high)
		FindAndSetMax(self.h3_DataC_fat, self.h3_DataC_pn, self.h3_DataC_pn_high)
		FindAndSetMax(self.h4_DataC_fat, self.h4_DataC_pn, self.h4_DataC_pn_high)
		FindAndSetMax(self.h5_DataC_fat, self.h5_DataC_pn, self.h5_DataC_pn_high)
		FindAndSetMax(self.h6_DataC_fat, self.h6_DataC_pn, self.h6_DataC_pn_high)
		FindAndSetMax(self.h7_DataC_fat, self.h7_DataC_pn, self.h7_DataC_pn_high)

		ROOT.gStyle.SetOptStat(0)

		c1_GJ = TCanvas()
		c1_GJ.cd()
		self.h1_GJ_sel.SetTitle("GJ Softdrop Mass")
		self.h1_GJ_sel.Draw("hist")
		self.h1_GJ_fat.Draw("same hist")
		self.h1_GJ_pn.Draw("same hist")
		self.h1_GJ_pn_high.Draw("same hist")
		l1_GJ = TLegend(.5, .6, .89, .89)
		l1_GJ.SetFillColor(0)
		l1_GJ.SetLineColor(0)
                l1_GJ.AddEntry(self.h1_GJ_sel, "Selected")
                l1_GJ.AddEntry(self.h1_GJ_fat, "Fat")
                l1_GJ.AddEntry(self.h1_GJ_pn, "PN")
                l1_GJ.AddEntry(self.h1_GJ_pn_high, "PN High")
                l1_GJ.Draw()
		gPad.SetLogy()
		c1_GJ.SaveAs("./plots/"+name+"_soft_GJ.png")
		c1_GJ.Close()
		
		c1_WG = TCanvas()
		c1_WG.cd()
		self.h1_WG_sel.SetTitle("WGamma Softdrop Mass")
		self.h1_WG_sel.Draw("hist")
		self.h1_WG_fat.Draw("same hist")
		self.h1_WG_pn.Draw("same hist")
		self.h1_WG_pn_high.Draw("same hist")
		l1_WG = TLegend(.5, .6, .89, .89)
		l1_WG.SetFillColor(0)
		l1_WG.SetLineColor(0)
                l1_WG.AddEntry(self.h1_WG_sel, "Selected")
                l1_WG.AddEntry(self.h1_WG_fat, "Fat")
                l1_WG.AddEntry(self.h1_WG_pn, "PN")
                l1_WG.AddEntry(self.h1_WG_pn_high, "PN High")
                l1_WG.Draw()
		gPad.SetLogy()
		c1_WG.SaveAs("./plots/"+name+"_soft_WG.png")
		c1_WG.Close()
	
		c1_ZG = TCanvas()
		c1_ZG.cd()
		self.h1_ZG_sel.SetTitle("ZGamma Softdrop Mass")
		self.h1_ZG_sel.Draw("hist")
		self.h1_ZG_fat.Draw("same hist")
		self.h1_ZG_pn.Draw("same hist")
		self.h1_ZG_pn_high.Draw("same hist")
		l1_ZG = TLegend(.5, .6, .89, .89)
		l1_ZG.SetFillColor(0)
		l1_ZG.SetLineColor(0)
                l1_ZG.AddEntry(self.h1_ZG_sel, "Selected")
                l1_ZG.AddEntry(self.h1_ZG_fat, "Fat")
                l1_ZG.AddEntry(self.h1_ZG_pn, "PN")
                l1_ZG.AddEntry(self.h1_ZG_pn_high, "PN High")
                l1_ZG.Draw()
		gPad.SetLogy()
		c1_ZG.SaveAs("./plots/"+name+"_soft_ZG.png")
		c1_ZG.Close()

		c1_M50 = TCanvas()
		c1_M50.cd()
		self.h1_M50_sel.SetTitle("M50 Softdrop Mass")
		self.h1_M50_sel.Draw("hist")
		self.h1_M50_fat.Draw("same hist")
		self.h1_M50_pn.Draw("same hist")
		self.h1_M50_pn_high.Draw("same hist")
		l1_M50 = TLegend(.5, .6, .89, .89)
		l1_M50.SetFillColor(0)
		l1_M50.SetLineColor(0)
                l1_M50.AddEntry(self.h1_M50_sel, "Selected")
                l1_M50.AddEntry(self.h1_M50_fat, "Fat")
                l1_M50.AddEntry(self.h1_M50_pn, "PN")
                l1_M50.AddEntry(self.h1_M50_pn_high, "PN High")
                l1_M50.Draw()
		gPad.SetLogy()
		c1_M50.SaveAs("./plots/"+name+"_soft_M50.png")
		c1_M50.Close()


		c1_DataC = TCanvas()
		c1_DataC.cd()
		self.h1_DataC_sel.SetTitle("DataC Softdrop Mass")
		self.h1_DataC_sel.Draw("hist")
		self.h1_DataC_fat.Draw("same hist")
		self.h1_DataC_pn.Draw("same hist")
		self.h1_DataC_pn_high.Draw("same hist")
		l1_DataC = TLegend(.5, .6, .89, .89)
		l1_DataC.SetFillColor(0)
		l1_DataC.SetLineColor(0)
                l1_DataC.AddEntry(self.h1_DataC_sel, "Selected")
                l1_DataC.AddEntry(self.h1_DataC_fat, "Fat")
                l1_DataC.AddEntry(self.h1_DataC_pn, "PN")
                l1_DataC.AddEntry(self.h1_DataC_pn_high, "PN High")
                l1_DataC.Draw()
		gPad.SetLogy()
		c1_DataC.SaveAs("./plots/"+name+"_soft_DataC.png")
		c1_DataC.Close()



		c2_GJ = TCanvas()
		c2_GJ.cd()
		self.h2_GJ_sel.SetTitle("GJ Jet pT")
		self.h2_GJ_sel.Draw("hist")
		self.h2_GJ_fat.Draw("same hist")
		self.h2_GJ_pn.Draw("same hist")
		self.h2_GJ_pn_high.Draw("same hist")
		l2_GJ = TLegend(.5, .6, .89, .89)
		l2_GJ.SetFillColor(0)
		l2_GJ.SetLineColor(0)
                l2_GJ.AddEntry(self.h2_GJ_sel, "Selected")
                l2_GJ.AddEntry(self.h2_GJ_fat, "Fat")
                l2_GJ.AddEntry(self.h2_GJ_pn, "PN")
                l2_GJ.AddEntry(self.h2_GJ_pn_high, "PN High")
                l2_GJ.Draw()
		gPad.SetLogy()
		c2_GJ.SaveAs("./plots/"+name+"_jet_pt_GJ.png")
		c2_GJ.Close()
		
		c2_WG = TCanvas()
		c2_WG.cd()
		self.h2_WG_sel.SetTitle("WGamma Jet pT")
		self.h2_WG_sel.Draw("hist")
		self.h2_WG_fat.Draw("same hist")
		self.h2_WG_pn.Draw("same hist")
		self.h2_WG_pn_high.Draw("same hist")
		l2_WG = TLegend(.5, .6, .89, .89)
		l2_WG.SetFillColor(0)
		l2_WG.SetLineColor(0)
                l2_WG.AddEntry(self.h2_WG_sel, "Selected")
                l2_WG.AddEntry(self.h2_WG_fat, "Fat")
                l2_WG.AddEntry(self.h2_WG_pn, "PN")
                l2_WG.AddEntry(self.h2_WG_pn_high, "PN High")
                l2_WG.Draw()
		gPad.SetLogy()
		c2_WG.SaveAs("./plots/"+name+"_jet_pt_WG.png")
		c2_WG.Close()
	
		c2_ZG = TCanvas()
		c2_ZG.cd()
		self.h2_ZG_sel.SetTitle("ZGamma Jet pT")
		self.h2_ZG_sel.Draw("hist")
		self.h2_ZG_fat.Draw("same hist")
		self.h2_ZG_pn.Draw("same hist")
		self.h2_ZG_pn_high.Draw("same hist")
		l2_ZG = TLegend(.5, .6, .89, .89)
		l2_ZG.SetFillColor(0)
		l2_ZG.SetLineColor(0)
                l2_ZG.AddEntry(self.h2_ZG_sel, "Selected")
                l2_ZG.AddEntry(self.h2_ZG_fat, "Fat")
                l2_ZG.AddEntry(self.h2_ZG_pn, "PN")
                l2_ZG.AddEntry(self.h2_ZG_pn_high, "PN High")
                l2_ZG.Draw()
		gPad.SetLogy()
		c2_ZG.SaveAs("./plots/"+name+"_jet_pt_ZG.png")
		c2_ZG.Close()

		c2_M50 = TCanvas()
		c2_M50.cd()
		self.h2_M50_sel.SetTitle("M50 Jet pT")
		self.h2_M50_sel.Draw("hist")
		self.h2_M50_fat.Draw("same hist")
		self.h2_M50_pn.Draw("same hist")
		self.h2_M50_pn_high.Draw("same hist")
		l2_M50 = TLegend(.5, .6, .89, .89)
		l2_M50.SetFillColor(0)
		l2_M50.SetLineColor(0)
                l2_M50.AddEntry(self.h2_M50_sel, "Selected")
                l2_M50.AddEntry(self.h2_M50_fat, "Fat")
                l2_M50.AddEntry(self.h2_M50_pn, "PN")
                l2_M50.AddEntry(self.h2_M50_pn_high, "PN High")
                l2_M50.Draw()
		gPad.SetLogy()
		c2_M50.SaveAs("./plots/"+name+"_jet_pt_M50.png")
		c2_M50.Close()
		
		c2_DataC = TCanvas()
		c2_DataC.cd()
		self.h2_DataC_sel.SetTitle("DataC Jet pT")
		self.h2_DataC_sel.Draw("hist")
		self.h2_DataC_fat.Draw("same hist")
		self.h2_DataC_pn.Draw("same hist")
		self.h2_DataC_pn_high.Draw("same hist")
		l2_DataC = TLegend(.5, .6, .89, .89)
		l2_DataC.SetFillColor(0)
		l2_DataC.SetLineColor(0)
                l2_DataC.AddEntry(self.h2_DataC_sel, "Selected")
                l2_DataC.AddEntry(self.h2_DataC_fat, "Fat")
                l2_DataC.AddEntry(self.h2_DataC_pn, "PN")
                l2_DataC.AddEntry(self.h2_DataC_pn_high, "PN High")
                l2_DataC.Draw()
		gPad.SetLogy()
		c2_DataC.SaveAs("./plots/"+name+"_jet_pt_DataC.png")
		c2_DataC.Close()

		c3_GJ = TCanvas()
		c3_GJ.cd()
		self.h3_GJ_fat.SetTitle("GJ ParticleNetMD QCD")
		self.h3_GJ_fat.Draw("hist")
		self.h3_GJ_pn.Draw("same hist")
		self.h3_GJ_pn_high.Draw("same hist")
		l3_GJ = TLegend(.5, .6, .89, .89)
		l3_GJ.SetFillColor(0)
		l3_GJ.SetLineColor(0)
                l3_GJ.AddEntry(self.h3_GJ_fat, "Fat")
                l3_GJ.AddEntry(self.h3_GJ_pn, "PN")
                l3_GJ.AddEntry(self.h3_GJ_pn_high, "PN High")
                l3_GJ.Draw()
		gPad.SetLogy()
		c3_GJ.SaveAs("./plots/"+name+"_pnQCD_GJ.png")
		c3_GJ.Close()
		
		c3_WG = TCanvas()
		c3_WG.cd()
		self.h3_WG_fat.SetTitle("WGamma ParticleNetMD QCD")
		self.h3_WG_fat.Draw("hist")
		self.h3_WG_pn.Draw("same hist")
		self.h3_WG_pn_high.Draw("same hist")
		l3_WG = TLegend(.5, .6, .89, .89)
		l3_WG.SetFillColor(0)
		l3_WG.SetLineColor(0)
                l3_WG.AddEntry(self.h3_WG_fat, "Fat")
                l3_WG.AddEntry(self.h3_WG_pn, "PN")
                l3_WG.AddEntry(self.h3_WG_pn_high, "PN High")
                l3_WG.Draw()
		gPad.SetLogy()
		c3_WG.SaveAs("./plots/"+name+"_pnQCD_WG.png")
		c3_WG.Close()
	
		c3_ZG = TCanvas()
		c3_ZG.cd()
		self.h3_ZG_fat.SetTitle("ZGamma ParticleNetMD QCD")
		self.h3_ZG_fat.Draw("hist")
		self.h3_ZG_pn.Draw("same hist")
		self.h3_ZG_pn_high.Draw("same hist")
		l3_ZG = TLegend(.5, .6, .89, .89)
		l3_ZG.SetFillColor(0)
		l3_ZG.SetLineColor(0)
                l3_ZG.AddEntry(self.h3_ZG_fat, "Fat")
                l3_ZG.AddEntry(self.h3_ZG_pn, "PN")
                l3_ZG.AddEntry(self.h3_ZG_pn_high, "PN High")
                l3_ZG.Draw()
		gPad.SetLogy()
		c3_ZG.SaveAs("./plots/"+name+"_pnQCD_ZG.png")
		c3_ZG.Close()

		c3_M50 = TCanvas()
		c3_M50.cd()
		self.h3_M50_fat.SetTitle("M50 ParticleNetMD QCD")
		self.h3_M50_fat.Draw("hist")
		self.h3_M50_pn.Draw("same hist")
		self.h3_M50_pn_high.Draw("same hist")
		l3_M50 = TLegend(.5, .6, .89, .89)
		l3_M50.SetFillColor(0)
		l3_M50.SetLineColor(0)
                l3_M50.AddEntry(self.h3_M50_fat, "Fat")
                l3_M50.AddEntry(self.h3_M50_pn, "PN")
                l3_M50.AddEntry(self.h3_M50_pn_high, "PN High")
                l3_M50.Draw()
		gPad.SetLogy()
		c3_M50.SaveAs("./plots/"+name+"_pnQCD_M50.png")
		c3_M50.Close()
		
		c3_DataC = TCanvas()
		c3_DataC.cd()
		self.h3_DataC_fat.SetTitle("DataC ParticleNetMD QCD")
		self.h3_DataC_fat.Draw("hist")
		self.h3_DataC_pn.Draw("same hist")
		self.h3_DataC_pn_high.Draw("same hist")
		l3_DataC = TLegend(.5, .6, .89, .89)
		l3_DataC.SetFillColor(0)
		l3_DataC.SetLineColor(0)
                l3_DataC.AddEntry(self.h3_DataC_fat, "Fat")
                l3_DataC.AddEntry(self.h3_DataC_pn, "PN")
                l3_DataC.AddEntry(self.h3_DataC_pn_high, "PN High")
                l3_DataC.Draw()
		gPad.SetLogy()
		c3_DataC.SaveAs("./plots/"+name+"_pnQCD_DataC.png")
		c3_DataC.Close()

		c4_GJ = TCanvas()
		c4_GJ.cd()
		self.h4_GJ_fat.SetTitle("GJ ParticleNetMD Xbb")
		self.h4_GJ_fat.Draw("hist")
		self.h4_GJ_pn.Draw("same hist")
		self.h4_GJ_pn_high.Draw("same hist")
		l4_GJ = TLegend(.5, .6, .89, .89)
		l4_GJ.SetFillColor(0)
		l4_GJ.SetLineColor(0)
                l4_GJ.AddEntry(self.h4_GJ_fat, "Fat")
                l4_GJ.AddEntry(self.h4_GJ_pn, "PN")
                l4_GJ.AddEntry(self.h4_GJ_pn_high, "PN High")
                l4_GJ.Draw()
		gPad.SetLogy()
		c4_GJ.SaveAs("./plots/"+name+"_pnXbb_GJ.png")
		c4_GJ.Close()
		
		c4_WG = TCanvas()
		c4_WG.cd()
		self.h4_WG_fat.SetTitle("WGamma ParticleNetMD Xbb")
		self.h4_WG_fat.Draw("hist")
		self.h4_WG_pn.Draw("same hist")
		self.h4_WG_pn_high.Draw("same hist")
		l4_WG = TLegend(.5, .6, .89, .89)
		l4_WG.SetFillColor(0)
		l4_WG.SetLineColor(0)
                l4_WG.AddEntry(self.h4_WG_fat, "Fat")
                l4_WG.AddEntry(self.h4_WG_pn, "PN")
                l4_WG.AddEntry(self.h4_WG_pn_high, "PN High")
                l4_WG.Draw()
		gPad.SetLogy()
		c4_WG.SaveAs("./plots/"+name+"_pnXbb_WG.png")
		c4_WG.Close()
	
		c4_ZG = TCanvas()
		c4_ZG.cd()
		self.h4_ZG_fat.SetTitle("ZGamma ParticleNetMD Xbb")
		self.h4_ZG_fat.Draw("hist")
		self.h4_ZG_pn.Draw("same hist")
		self.h4_ZG_pn_high.Draw("same hist")
		l4_ZG = TLegend(.5, .6, .89, .89)
		l4_ZG.SetFillColor(0)
		l4_ZG.SetLineColor(0)
                l4_ZG.AddEntry(self.h4_ZG_fat, "Fat")
                l4_ZG.AddEntry(self.h4_ZG_pn, "PN")
                l4_ZG.AddEntry(self.h4_ZG_pn_high, "PN High")
                l4_ZG.Draw()
		gPad.SetLogy()
		c4_ZG.SaveAs("./plots/"+name+"_pnXbb_ZG.png")
		c4_ZG.Close()

		c4_M50 = TCanvas()
		c4_M50.cd()
		self.h4_M50_fat.SetTitle("M50 ParticleNetMD Xbb")
		self.h4_M50_fat.Draw("hist")
		self.h4_M50_pn.Draw("same hist")
		self.h4_M50_pn_high.Draw("same hist")
		l4_M50 = TLegend(.5, .6, .89, .89)
		l4_M50.SetFillColor(0)
		l4_M50.SetLineColor(0)
                l4_M50.AddEntry(self.h4_M50_fat, "Fat")
                l4_M50.AddEntry(self.h4_M50_pn, "PN")
                l4_M50.AddEntry(self.h4_M50_pn_high, "PN High")
                l4_M50.Draw()
		gPad.SetLogy()
		c4_M50.SaveAs("./plots/"+name+"_pnXbb_M50.png")
		c4_M50.Close()
		
		c4_DataC = TCanvas()
		c4_DataC.cd()
		self.h4_DataC_fat.SetTitle("DataC ParticleNetMD Xbb")
		self.h4_DataC_fat.Draw("hist")
		self.h4_DataC_pn.Draw("same hist")
		self.h4_DataC_pn_high.Draw("same hist")
		l4_DataC = TLegend(.5, .6, .89, .89)
		l4_DataC.SetFillColor(0)
		l4_DataC.SetLineColor(0)
                l4_DataC.AddEntry(self.h4_DataC_fat, "Fat")
                l4_DataC.AddEntry(self.h4_DataC_pn, "PN")
                l4_DataC.AddEntry(self.h4_DataC_pn_high, "PN High")
                l4_DataC.Draw()
		gPad.SetLogy()
		c4_DataC.SaveAs("./plots/"+name+"_pnXbb_DataC.png")
		c4_DataC.Close()

		c5_GJ = TCanvas()
		c5_GJ.cd()
		self.h5_GJ_fat.SetTitle("GJ ParticleNetMD Xcc")
		self.h5_GJ_fat.Draw("hist")
		self.h5_GJ_pn.Draw("same hist")
		self.h5_GJ_pn_high.Draw("same hist")
		l5_GJ = TLegend(.5, .6, .89, .89)
		l5_GJ.SetFillColor(0)
		l5_GJ.SetLineColor(0)
                l5_GJ.AddEntry(self.h5_GJ_fat, "Fat")
                l5_GJ.AddEntry(self.h5_GJ_pn, "PN")
                l5_GJ.AddEntry(self.h5_GJ_pn_high, "PN High")
                l5_GJ.Draw()
		gPad.SetLogy()
		c5_GJ.SaveAs("./plots/"+name+"_pnXcc_GJ.png")
		c5_GJ.Close()
		
		c5_WG = TCanvas()
		c5_WG.cd()
		self.h5_WG_fat.SetTitle("WGamma ParticleNetMD Xcc")
		self.h5_WG_fat.Draw("hist")
		self.h5_WG_pn.Draw("same hist")
		self.h5_WG_pn_high.Draw("same hist")
		l5_WG = TLegend(.5, .6, .89, .89)
		l5_WG.SetFillColor(0)
		l5_WG.SetLineColor(0)
                l5_WG.AddEntry(self.h5_WG_fat, "Fat")
                l5_WG.AddEntry(self.h5_WG_pn, "PN")
                l5_WG.AddEntry(self.h5_WG_pn_high, "PN High")
                l5_WG.Draw()
		gPad.SetLogy()
		c5_WG.SaveAs("./plots/"+name+"_pnXcc_WG.png")
		c5_WG.Close()
	
		c5_ZG = TCanvas()
		c5_ZG.cd()
		self.h5_ZG_fat.SetTitle("ZGamma ParticleNetMD Xcc")
		self.h5_ZG_fat.Draw("hist")
		self.h5_ZG_pn.Draw("same hist")
		self.h5_ZG_pn_high.Draw("same hist")
		l5_ZG = TLegend(.5, .6, .89, .89)
		l5_ZG.SetFillColor(0)
		l5_ZG.SetLineColor(0)
                l5_ZG.AddEntry(self.h5_ZG_fat, "Fat")
                l5_ZG.AddEntry(self.h5_ZG_pn, "PN")
                l5_ZG.AddEntry(self.h5_ZG_pn_high, "PN High")
                l5_ZG.Draw()
		gPad.SetLogy()
		c5_ZG.SaveAs("./plots/"+name+"_pnXcc_ZG.png")
		c5_ZG.Close()

		c5_M50 = TCanvas()
		c5_M50.cd()
		self.h5_M50_fat.SetTitle("M50 ParticleNetMD Xcc")
		self.h5_M50_fat.Draw("hist")
		self.h5_M50_pn.Draw("same hist")
		self.h5_M50_pn_high.Draw("same hist")
		l5_M50 = TLegend(.5, .6, .89, .89)
		l5_M50.SetFillColor(0)
		l5_M50.SetLineColor(0)
                l5_M50.AddEntry(self.h5_M50_fat, "Fat")
                l5_M50.AddEntry(self.h5_M50_pn, "PN")
                l5_M50.AddEntry(self.h5_M50_pn_high, "PN High")
                l5_M50.Draw()
		gPad.SetLogy()
		c5_M50.SaveAs("./plots/"+name+"_pnXcc_M50.png")
		c5_M50.Close()
		
		c5_DataC = TCanvas()
		c5_DataC.cd()
		self.h5_DataC_fat.SetTitle("DataC ParticleNetMD Xcc")
		self.h5_DataC_fat.Draw("hist")
		self.h5_DataC_pn.Draw("same hist")
		self.h5_DataC_pn_high.Draw("same hist")
		l5_DataC = TLegend(.5, .6, .89, .89)
		l5_DataC.SetFillColor(0)
		l5_DataC.SetLineColor(0)
                l5_DataC.AddEntry(self.h5_DataC_fat, "Fat")
                l5_DataC.AddEntry(self.h5_DataC_pn, "PN")
                l5_DataC.AddEntry(self.h5_DataC_pn_high, "PN High")
                l5_DataC.Draw()
		gPad.SetLogy()
		c5_DataC.SaveAs("./plots/"+name+"_pnXcc_DataC.png")
		c5_DataC.Close()

		c6_GJ = TCanvas()
		c6_GJ.cd()
		self.h6_GJ_fat.SetTitle("GJ ParticleNetMD Xqq")
		self.h6_GJ_fat.Draw("hist")
		self.h6_GJ_pn.Draw("same hist")
		self.h6_GJ_pn_high.Draw("same hist")
		l6_GJ = TLegend(.5, .6, .89, .89)
		l6_GJ.SetFillColor(0)
		l6_GJ.SetLineColor(0)
                l6_GJ.AddEntry(self.h6_GJ_fat, "Fat")
                l6_GJ.AddEntry(self.h6_GJ_pn, "PN")
                l6_GJ.AddEntry(self.h6_GJ_pn_high, "PN High")
                l6_GJ.Draw()
		gPad.SetLogy()
		c6_GJ.SaveAs("./plots/"+name+"_pnXqq_GJ.png")
		c6_GJ.Close()
		
		c6_WG = TCanvas()
		c6_WG.cd()
		self.h6_WG_fat.SetTitle("WGamma ParticleNetMD Xqq")
		self.h6_WG_fat.Draw("hist")
		self.h6_WG_pn.Draw("same hist")
		self.h6_WG_pn_high.Draw("same hist")
		l6_WG = TLegend(.5, .6, .89, .89)
		l6_WG.SetFillColor(0)
		l6_WG.SetLineColor(0)
                l6_WG.AddEntry(self.h6_WG_fat, "Fat")
                l6_WG.AddEntry(self.h6_WG_pn, "PN")
                l6_WG.AddEntry(self.h6_WG_pn_high, "PN High")
                l6_WG.Draw()
		gPad.SetLogy()
		c6_WG.SaveAs("./plots/"+name+"_pnXqq_WG.png")
		c6_WG.Close()
	
		c6_ZG = TCanvas()
		c6_ZG.cd()
		self.h6_ZG_fat.SetTitle("ZGamma ParticleNetMD Xqq")
		self.h6_ZG_fat.Draw("hist")
		self.h6_ZG_pn.Draw("same hist")
		self.h6_ZG_pn_high.Draw("same hist")
		l6_ZG = TLegend(.5, .6, .89, .89)
		l6_ZG.SetFillColor(0)
		l6_ZG.SetLineColor(0)
                l6_ZG.AddEntry(self.h6_ZG_fat, "Fat")
                l6_ZG.AddEntry(self.h6_ZG_pn, "PN")
                l6_ZG.AddEntry(self.h6_ZG_pn_high, "PN High")
                l6_ZG.Draw()
		gPad.SetLogy()
		c6_ZG.SaveAs("./plots/"+name+"_pnXqq_ZG.png")
		c6_ZG.Close()

		c6_M50 = TCanvas()
		c6_M50.cd()
		self.h6_M50_fat.SetTitle("M50 ParticleNetMD Xqq")
		self.h6_M50_fat.Draw("hist")
		self.h6_M50_pn.Draw("same hist")
		self.h6_M50_pn_high.Draw("same hist")
		l6_M50 = TLegend(.5, .6, .89, .89)
		l6_M50.SetFillColor(0)
		l6_M50.SetLineColor(0)
                l6_M50.AddEntry(self.h6_M50_fat, "Fat")
                l6_M50.AddEntry(self.h6_M50_pn, "PN")
                l6_M50.AddEntry(self.h6_M50_pn_high, "PN High")
                l6_M50.Draw()
		gPad.SetLogy()
		c6_M50.SaveAs("./plots/"+name+"_pnXqq_M50.png")
		c6_M50.Close()

		c6_DataC = TCanvas()
		c6_DataC.cd()
		self.h6_DataC_fat.SetTitle("DataC ParticleNetMD Xqq")
		self.h6_DataC_fat.Draw("hist")
		self.h6_DataC_pn.Draw("same hist")
		self.h6_DataC_pn_high.Draw("same hist")
		l6_DataC = TLegend(.5, .6, .89, .89)
		l6_DataC.SetFillColor(0)
		l6_DataC.SetLineColor(0)
                l6_DataC.AddEntry(self.h6_DataC_fat, "Fat")
                l6_DataC.AddEntry(self.h6_DataC_pn, "PN")
                l6_DataC.AddEntry(self.h6_DataC_pn_high, "PN High")
                l6_DataC.Draw()
		gPad.SetLogy()
		c6_DataC.SaveAs("./plots/"+name+"_pnXqq_DataC.png")
		c6_DataC.Close()


		c7_GJ = TCanvas()
		c7_GJ.cd()
		self.h7_GJ_fat.SetTitle("GJ ParticleNetMD Two-Pronged Jet Score")
		self.h7_GJ_fat.Draw("hist")
		self.h7_GJ_pn.Draw("same hist")
		self.h7_GJ_pn_high.Draw("same hist")
		l6_GJ = TLegend(.5, .2, .89, .4)
		l6_GJ.SetFillColor(0)
		l6_GJ.SetLineColor(0)
                l6_GJ.AddEntry(self.h7_GJ_fat, "Fat")
                l6_GJ.AddEntry(self.h7_GJ_pn, "PN")
                l6_GJ.AddEntry(self.h7_GJ_pn_high, "PN High")
                l6_GJ.Draw()
		gPad.SetLogy()
		c7_GJ.SaveAs("./plots/"+name+"_pnAllQQ_GJ.png")
		c7_GJ.Close()
		
		c7_WG = TCanvas()
		c7_WG.cd()
		self.h7_WG_fat.SetTitle("WGamma ParticleNetMD Two-Pronged Jet Score")
		self.h7_WG_fat.Draw("hist")
		self.h7_WG_pn.Draw("same hist")
		self.h7_WG_pn_high.Draw("same hist")
		l6_WG = TLegend(.5, .2, .89, .4)
		l6_WG.SetFillColor(0)
		l6_WG.SetLineColor(0)
                l6_WG.AddEntry(self.h7_WG_fat, "Fat")
                l6_WG.AddEntry(self.h7_WG_pn, "PN")
                l6_WG.AddEntry(self.h7_WG_pn_high, "PN High")
                l6_WG.Draw()
		gPad.SetLogy()
		c7_WG.SaveAs("./plots/"+name+"_pnAllQQ_WG.png")
		c7_WG.Close()
	
		c7_ZG = TCanvas()
		c7_ZG.cd()
		self.h7_ZG_fat.SetTitle("ZGamma ParticleNetMD Two-Pronged Jet Score")
		self.h7_ZG_fat.Draw("hist")
		self.h7_ZG_pn.Draw("same hist")
		self.h7_ZG_pn_high.Draw("same hist")
		l6_ZG = TLegend(.5, .2, .89, .4)
		l6_ZG.SetFillColor(0)
		l6_ZG.SetLineColor(0)
                l6_ZG.AddEntry(self.h7_ZG_fat, "Fat")
                l6_ZG.AddEntry(self.h7_ZG_pn, "PN")
                l6_ZG.AddEntry(self.h7_ZG_pn_high, "PN High")
                l6_ZG.Draw()
		gPad.SetLogy()
		c7_ZG.SaveAs("./plots/"+name+"_pnAllQQ_ZG.png")
		c7_ZG.Close()

		c7_M50 = TCanvas()
		c7_M50.cd()
		self.h7_M50_fat.SetTitle("M50 ParticleNetMD Two-Pronged Jet Score")
		self.h7_M50_fat.Draw("hist")
		self.h7_M50_pn.Draw("same hist")
		self.h7_M50_pn_high.Draw("same hist")
		l6_M50 = TLegend(.5, .2, .89, .4)
		l6_M50.SetFillColor(0)
		l6_M50.SetLineColor(0)
                l6_M50.AddEntry(self.h7_M50_fat, "Fat")
                l6_M50.AddEntry(self.h7_M50_pn, "PN")
                l6_M50.AddEntry(self.h7_M50_pn_high, "PN High")
                l6_M50.Draw()
		gPad.SetLogy()
		c7_M50.SaveAs("./plots/"+name+"_pnAllQQ_M50.png")
		c7_M50.Close()

		c7_DataC = TCanvas()
		c7_DataC.cd()
		self.h7_DataC_fat.SetTitle("DataC ParticleNetMD Two-Pronged Jet Score")
		self.h7_DataC_fat.Draw("hist")
		self.h7_DataC_pn.Draw("same hist")
		self.h7_DataC_pn_high.Draw("same hist")
		l6_DataC = TLegend(.5, .2, .89, .4)
		l6_DataC.SetFillColor(0)
		l6_DataC.SetLineColor(0)
                l6_DataC.AddEntry(self.h7_DataC_fat, "Fat")
                l6_DataC.AddEntry(self.h7_DataC_pn, "PN")
                l6_DataC.AddEntry(self.h7_DataC_pn_high, "PN High")
                l6_DataC.Draw()
		gPad.SetLogy()
		c7_DataC.SaveAs("./plots/"+name+"_pnAllQQ_DataC.png")
		c7_DataC.Close()








